# Generated by Django 4.2.20 on 2025-05-03 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YourOrganModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TitleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MetaTitle', models.CharField(max_length=255)),
                ('MetaContributors', models.TextField(blank=True)),
                ('MetaPublisher', models.CharField(blank=True, max_length=255)),
                ('MetaSubject', models.CharField(blank=True, max_length=255)),
                ('MetaShotList', models.TextField(blank=True)),
                ('MetaAppendixInfo', models.TextField(blank=True)),
                ('MetaContent', models.TextField(blank=True)),
                ('MetaDescription', models.TextField(blank=True)),
                ('MetaSubFeatures', models.TextField(blank=True)),
                ('MetaShowDate', models.DateField(blank=True, null=True)),
                ('Title', models.CharField(max_length=255)),
                ('AlbumTitle', models.CharField(blank=True, max_length=255)),
                ('EpisodeTitle', models.CharField(blank=True, max_length=255)),
                ('Episodesequence', models.IntegerField(blank=True, null=True)),
                ('PublishmentStartYear', models.IntegerField(blank=True, null=True)),
                ('PublishmentEndYear', models.IntegerField(blank=True, null=True)),
                ('PublishmentCalendar', models.CharField(blank=True, max_length=50)),
                ('AgeGroup', models.CharField(blank=True, max_length=50)),
                ('LangID', models.CharField(blank=True, max_length=50)),
                ('EpisodeCount', models.IntegerField(blank=True, null=True)),
                ('Duration', models.DurationField(blank=True, null=True)),
                ('final_status', models.BooleanField(default=False)),
                ('base_code', models.CharField(blank=True, max_length=100)),
                ('father_code', models.CharField(blank=True, max_length=100)),
                ('new_title_code', models.CharField(editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metadata.yourorganmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
